// <auto-generated />
using System;
using InRemedy.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InRemedy.Api.Data.Migrations
{
    [DbContext(typeof(InRemedyDbContext))]
    [Migration("20260324213920_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InRemedy.Api.Models.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("LastSyncDateTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("OsBuild")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OsVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryUser")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdateRing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceName");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("InRemedy.Api.Models.ImportBatch", b =>
                {
                    b.Property<Guid>("ImportBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DuplicateOfImportBatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("ErrorRows")
                        .HasColumnType("integer");

                    b.Property<string>("FileHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("ImportType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("ImportedRows")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer");

                    b.HasKey("ImportBatchId");

                    b.HasIndex("FileHashSha256");

                    b.HasIndex("StartedUtc");

                    b.ToTable("ImportBatches");
                });

            modelBuilder.Entity("InRemedy.Api.Models.ImportError", b =>
                {
                    b.Property<Guid>("ImportErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("RowSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ImportErrorId");

                    b.HasIndex("ImportBatchId");

                    b.ToTable("ImportErrors");
                });

            modelBuilder.Entity("InRemedy.Api.Models.Remediation", b =>
                {
                    b.Property<Guid>("RemediationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetectionScriptVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RemediationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RemediationScriptVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RemediationId");

                    b.HasIndex("RemediationName");

                    b.ToTable("Remediations");
                });

            modelBuilder.Entity("InRemedy.Api.Models.RemediationResult", b =>
                {
                    b.Property<Guid>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetectionOutputRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("text");

                    b.Property<DateTime>("IngestionTimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OutputCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RemediationAttemptedFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RemediationId")
                        .HasColumnType("uuid");

                    b.Property<string>("RemediationOutputRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RemediationSucceededFlag")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RunTimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScriptVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ResultId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("RemediationId", "DeviceId", "RunTimestampUtc");

                    b.ToTable("RemediationResults");
                });

            modelBuilder.Entity("InRemedy.Api.Models.SavedView", b =>
                {
                    b.Property<Guid>("SavedViewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ViewDefinitionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SavedViewId");

                    b.HasIndex("OwnerUserId", "PageType", "IsDefault");

                    b.ToTable("SavedViews");
                });

            modelBuilder.Entity("InRemedy.Api.Models.ImportError", b =>
                {
                    b.HasOne("InRemedy.Api.Models.ImportBatch", "ImportBatch")
                        .WithMany("Errors")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("InRemedy.Api.Models.RemediationResult", b =>
                {
                    b.HasOne("InRemedy.Api.Models.Device", "Device")
                        .WithMany("Results")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InRemedy.Api.Models.Remediation", "Remediation")
                        .WithMany("Results")
                        .HasForeignKey("RemediationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Remediation");
                });

            modelBuilder.Entity("InRemedy.Api.Models.Device", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("InRemedy.Api.Models.ImportBatch", b =>
                {
                    b.Navigation("Errors");
                });

            modelBuilder.Entity("InRemedy.Api.Models.Remediation", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
